### ISSUE TITLE
YouTube channel

### ISSUE THREAD

**Issue by davisjam** [mod0/csgc-website#64]
If we plan to record our academically-inclined events, we may want to consider a YouTube channel.

This would let us relocate the video from #63, and we would need to update that link.

**Comment by davisjam** [comment]
@ayaankazerouni @franceme Thoughts?

**Comment by franceme** [comment]
For academically-inclined events I think it'd be fine, as long as the expectation is set for the recording.

Though a minor issue, there'd be an inconsistency between the academic events videos and other events such as #54 (the industry jobs event).

**Comment by ayaankazerouni** [comment]
We can just upload the video of the industry jobs event. Unless we lock it to vt email addresses, we need to make sure it's ok with the panelists beforehand.

**Comment by davisjam** [comment]
I think we would want to lock to VT email addresses by default. I don't see consent issues if we do that.

**Comment by franceme** [comment]
I've only uploaded a few videos to Youtube awhile ago, but is there a way to set a Youtube video to a specific email account type?
I realize it can be shared via link only but a corner case of someone sharing the url would bypass that.

If that's possible I don't see a problem.

**Comment by davisjam** [comment]
Actually it looks like YouTube's only content restriction options are:

1. Private (share with individual emails only)
2. Public

unless you have a fancy account with Google.

HOWEVER: If we put the video on our website (as in #63), how is that different from putting it on YouTube?

**Comment by franceme** [comment]
The only reason to keep the videos hosted via the Google Drive is to ensure only VT students can watch it.

A more public video such as #63 (assuming the participants agree) would be fine to host on YouTube.
My only hesitation is the two different locations of hosting videos.

**Comment by davisjam** [comment]
Ah, right, the video is hosted on Drive (where we have more fine-grained access control) and not directly on the CS@VT hosting. My bad.

I conclude that keeping the videos on the Drive is a good approach.
