### ISSUE TITLE
'Graduate students' link at cs.vt.edu/people is broken

### ISSUE THREAD

**Issue by ayaankazerouni** [mod0/csgc-website#8]
The link points to `csgrad.cs.vt.edu/homepages`. We may not be able to control what's on the CS website, but since it's pointing at the CS GC domain we should work on setting up a list of links to grad student homepages if they exist so that there's not a 404 error.

**Comment by davisjam** [comment]
I believe replacing this site is one of Dr. Shaffer's goals.

**Comment by ayaankazerouni** [comment]
Link is fixed now.
