### ISSUE TITLE
New page with officer bios

### ISSUE THREAD

**Issue by davisjam** [mod0/csgc-website#9]
@jwenskovitch is collecting these and should put up a page when he has them all.

**Comment by davisjam** [comment]
Partially addressed in #12, but perhaps some thumbnail pictures and more legitimate biographies would be helpful. @jwenskovitch.

**Comment by ayaankazerouni** [comment]
If everyone has linked their websites and thumbnails to the GPC grad school list, we could use those image URLs.

**Comment by davisjam** [comment]
Good idea.

**Comment by davisjam** [comment]
Fixed by #22
